---
- name: Get Theme
  git:
    force: "yes"
    depth: "1"
    repo: "{{ iw_theme_git_repo }}"
    version: "{{ iw_theme_git_version | default('master') }}"
    dest: "{{ iw_theme_tmp_dir }}"

- name: Install Special Theme Files
  copy:
    src: "{{ iw_theme_tmp_dir }}/siteworx/{{ item.src }}"
    dest: "{{ iw_homedir }}{{ item.dest }}"
    remote_src: "yes"
    mode: 0644
    owner: "{{ iw_unix_user }}"
    group: "{{ iw_unix_group }}"
  with_items:
    - { src: 'skel.html', dest: '/etc/skel/index.html' }
    - { src: 'disabled.html', dest: '/var/errors/disabled/index.html' }
    - { src: 'overage.html', dest: '/var/errors/overage/index.html' }

- name: Remove Special Theme Files
  file:
    path: "{{ iw_theme_tmp_dir }}/siteworx/{{ item }}"
    state: "absent"
  with_items:
    - "overage.html"
    - "disabled.html"
    - "skel.html"

- name: Remove The Theme .git Dir
  file:
    path: "{{ iw_theme_tmp_dir }}/.git/"
    state: "absent"

- name: Zip Theme
  archive:
    path: "{{ iw_theme_tmp_dir }}/*"
    dest: "{{ iw_theme_tmp_dir }}.zip"
    remove: "yes"
    format: "zip"

- name: Install Theme
  command: >
    nodeworx
      -unv
      -c Themes
      -a add
      --archive {{ iw_theme_tmp_dir }}.zip
  tags:
    - skip_ansible_lint

- name: Set Theme as Default
  command: >
    nodeworx -un
    -c Users
    -a edit
    --user {{ iw_master_email }}
    --theme {{ iw_theme_name }}
  tags:
    - skip_ansible_lint

- name: Remove Tmp Theme
  file:
    path: "{{ iw_theme_tmp_dir }}.zip"
    state: "absent"
